version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"    
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads 
    environment:
      - NODE_ENV=production
